# Generated by Django 3.1.3 on 2020-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdata',
            name='bank_acc',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='orgdata',
            name='bank_ifsc',
            field=models.CharField(default='0000', max_length=15),
        ),
        migrations.AddField(
            model_name='orgdata',
            name='upi_id',
            field=models.CharField(default='upi@upi.com', max_length=15),
        ),
    ]
