# Generated by Django 3.1.3 on 2020-11-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201129_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdata',
            name='myfile',
            field=models.ImageField(upload_to='org'),
        ),
    ]
