# Generated by Django 3.1.3 on 2020-11-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201130_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdata',
            name='myfile',
            field=models.ImageField(upload_to='org/'),
        ),
        migrations.AlterField(
            model_name='orgdata',
            name='need_desc',
            field=models.CharField(max_length=100),
        ),
    ]
