# Generated by Django 3.1.3 on 2020-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201130_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdata',
            name='need_desc',
            field=models.CharField(max_length=150),
        ),
    ]
